FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/ORM.py ./ingestion/ORM.py 
COPY ingestion/ingest.py ./ingestion/ingest.py
COPY datas/commandes_clean.csv ./datas/commandes_clean.csv

CMD ["python", "-m", "ingestion.ingest"]